development:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  user: fedoraAdmin
  password: fedoraAdmin
  validateChecksum: true
test: &TEST  
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora-test
  user: fedoraAdmin
  password: fedoraAdmin
  validateChecksum: true
integration:
  url: http://_USER_:_PASSWORD_@_HOST_:_PORT_/_fedora_integration_instance_
  user: _USER_
  password: _PASSWORD_
production:
  url: http://_USER_:_PASSWORD_@_HOST_:_PORT_/_fedora_production_instance_
  user: _USER_
  password: _PASSWORD_
  validateChecksum: true
cucumber:
  <<: *TEST
dlvecnet:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8080/fedora
  user: fedoraAdmin
  password: fedoraAdmin
