development:
  host: libvirt1.library.nd.edu
  port: 6379
test:
  host: libvirt1.library.nd.edu
  port: 6379
integration:
  host: localhost
  port: 6379
production:
  host: localhost
  port: 6379
resque:
  host: libvirt1.library.nd.edu
  port: 6379
dlvecnet:
  host: localhost
  port: 6379
